//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conqueros_Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idiomaES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idiomaES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conqueros_Calculator.Properties.idiomaES", typeof(idiomaES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceite de linaza.
        /// </summary>
        internal static string aceitelinaza {
            get {
                return ResourceManager.GetString("aceitelinaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerce.
        /// </summary>
        internal static string alerce {
            get {
                return ResourceManager.GetString("alerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algodon alta calidad.
        /// </summary>
        internal static string algodonAltaCalidad {
            get {
                return ResourceManager.GetString("algodonAltaCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algodon media calidad.
        /// </summary>
        internal static string algodonMediaCalidad {
            get {
                return ResourceManager.GetString("algodonMediaCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algodon mejor calidad.
        /// </summary>
        internal static string algodonMejorCalidad {
            get {
                return ResourceManager.GetString("algodonMejorCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algodon de montaña.
        /// </summary>
        internal static string algodonMontaña {
            get {
                return ResourceManager.GetString("algodonMontaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algodon nube.
        /// </summary>
        internal static string algodonNube {
            get {
                return ResourceManager.GetString("algodonNube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algodon poca calidad.
        /// </summary>
        internal static string algodonPocaCalidad {
            get {
                return ResourceManager.GetString("algodonPocaCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almizcle.
        /// </summary>
        internal static string almizcle {
            get {
                return ResourceManager.GetString("almizcle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alumbre.
        /// </summary>
        internal static string alumbre {
            get {
                return ResourceManager.GetString("alumbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbar.
        /// </summary>
        internal static string ambar {
            get {
                return ResourceManager.GetString("ambar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arenisca.
        /// </summary>
        internal static string arenisca {
            get {
                return ResourceManager.GetString("arenisca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bauxita de montaña.
        /// </summary>
        internal static string bauxitamontaña {
            get {
                return ResourceManager.GetString("bauxitamontaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piel de cabra.
        /// </summary>
        internal static string cabra {
            get {
                return ResourceManager.GetString("cabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calamina.
        /// </summary>
        internal static string calamina {
            get {
                return ResourceManager.GetString("calamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calcopirita.
        /// </summary>
        internal static string calcopirita {
            get {
                return ResourceManager.GetString("calcopirita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calcosina.
        /// </summary>
        internal static string calcosina {
            get {
                return ResourceManager.GetString("calcosina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cáñamo.
        /// </summary>
        internal static string cañamo {
            get {
                return ResourceManager.GetString("cañamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carbón.
        /// </summary>
        internal static string carbon {
            get {
                return ResourceManager.GetString("carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cedro.
        /// </summary>
        internal static string cedro {
            get {
                return ResourceManager.GetString("cedro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piel de cerdo.
        /// </summary>
        internal static string cerdo {
            get {
                return ResourceManager.GetString("cerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobre en bruto.
        /// </summary>
        internal static string cobreBruto {
            get {
                return ResourceManager.GetString("cobreBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobre mejorado.
        /// </summary>
        internal static string cobreMejorado {
            get {
                return ResourceManager.GetString("cobreMejorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobreMejorado.
        /// </summary>
        internal static string cobreMejorado1 {
            get {
                return ResourceManager.GetString("cobreMejorado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobre puro.
        /// </summary>
        internal static string cobrePuro {
            get {
                return ResourceManager.GetString("cobrePuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobrePuro.
        /// </summary>
        internal static string cobrePuro1 {
            get {
                return ResourceManager.GetString("cobrePuro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobre refinado.
        /// </summary>
        internal static string cobreRefinado {
            get {
                return ResourceManager.GetString("cobreRefinado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobreRefinado.
        /// </summary>
        internal static string cobreRefinado1 {
            get {
                return ResourceManager.GetString("cobreRefinado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuero curtido.
        /// </summary>
        internal static string cueroCurtido {
            get {
                return ResourceManager.GetString("cueroCurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroCurtido.
        /// </summary>
        internal static string cueroCurtido1 {
            get {
                return ResourceManager.GetString("cueroCurtido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuero hervido.
        /// </summary>
        internal static string cueroHervido {
            get {
                return ResourceManager.GetString("cueroHervido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroHervido.
        /// </summary>
        internal static string cueroHervido1 {
            get {
                return ResourceManager.GetString("cueroHervido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuero perfeccionado.
        /// </summary>
        internal static string cueroPerfeccionado {
            get {
                return ResourceManager.GetString("cueroPerfeccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroPerfeccionado.
        /// </summary>
        internal static string cueroPerfeccionado1 {
            get {
                return ResourceManager.GetString("cueroPerfeccionado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuero Tratado.
        /// </summary>
        internal static string cueroTratado {
            get {
                return ResourceManager.GetString("cueroTratado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroTratado.
        /// </summary>
        internal static string cueroTratado1 {
            get {
                return ResourceManager.GetString("cueroTratado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuprita.
        /// </summary>
        internal static string cuprita {
            get {
                return ResourceManager.GetString("cuprita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a digenita.
        /// </summary>
        internal static string digenita {
            get {
                return ResourceManager.GetString("digenita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estaño.
        /// </summary>
        internal static string estaño {
            get {
                return ResourceManager.GetString("estaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fosforo.
        /// </summary>
        internal static string fosforo {
            get {
                return ResourceManager.GetString("fosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fresno.
        /// </summary>
        internal static string fresno {
            get {
                return ResourceManager.GetString("fresno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goma laca.
        /// </summary>
        internal static string gomalaca {
            get {
                return ResourceManager.GetString("gomalaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Granate.
        /// </summary>
        internal static string granate {
            get {
                return ResourceManager.GetString("granate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Granito.
        /// </summary>
        internal static string granito {
            get {
                return ResourceManager.GetString("granito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hematita.
        /// </summary>
        internal static string hematita {
            get {
                return ResourceManager.GetString("hematita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hierro en bruto.
        /// </summary>
        internal static string hierroBruto {
            get {
                return ResourceManager.GetString("hierroBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hierro forjado.
        /// </summary>
        internal static string hierroForjado {
            get {
                return ResourceManager.GetString("hierroForjado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hierro fundido.
        /// </summary>
        internal static string hierroFundido {
            get {
                return ResourceManager.GetString("hierroFundido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hierro puro.
        /// </summary>
        internal static string hierroPuro {
            get {
                return ResourceManager.GetString("hierroPuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limonita.
        /// </summary>
        internal static string limonita {
            get {
                return ResourceManager.GetString("limonita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lino.
        /// </summary>
        internal static string lino {
            get {
                return ResourceManager.GetString("lino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madera alisada.
        /// </summary>
        internal static string maderaAlisada {
            get {
                return ResourceManager.GetString("maderaAlisada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madera compuesta.
        /// </summary>
        internal static string maderaCompuesta {
            get {
                return ResourceManager.GetString("maderaCompuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madera seca.
        /// </summary>
        internal static string maderaSeca {
            get {
                return ResourceManager.GetString("maderaSeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Magnetita.
        /// </summary>
        internal static string magnetita {
            get {
                return ResourceManager.GetString("magnetita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manganeso negro.
        /// </summary>
        internal static string manganesoNegro {
            get {
                return ResourceManager.GetString("manganesoNegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mármol.
        /// </summary>
        internal static string marmol {
            get {
                return ResourceManager.GetString("marmol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minio.
        /// </summary>
        internal static string minio {
            get {
                return ResourceManager.GetString("minio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nitrato de potasio.
        /// </summary>
        internal static string nitratopotasio {
            get {
                return ResourceManager.GetString("nitratopotasio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piel de oveja.
        /// </summary>
        internal static string oveja {
            get {
                return ResourceManager.GetString("oveja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pelaje lobo de montaña.
        /// </summary>
        internal static string pelajelobomontaña {
            get {
                return ResourceManager.GetString("pelajelobomontaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pelajes.
        /// </summary>
        internal static string pelajes {
            get {
                return ResourceManager.GetString("pelajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piedra en bruto.
        /// </summary>
        internal static string piedraBruto {
            get {
                return ResourceManager.GetString("piedraBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piedra cortada.
        /// </summary>
        internal static string piedraCortada {
            get {
                return ResourceManager.GetString("piedraCortada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piedra detallada.
        /// </summary>
        internal static string piedraDetallada {
            get {
                return ResourceManager.GetString("piedraDetallada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piedra lunar.
        /// </summary>
        internal static string piedralunar {
            get {
                return ResourceManager.GetString("piedralunar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piedra perfeccionada.
        /// </summary>
        internal static string piedraPerfeccionada {
            get {
                return ResourceManager.GetString("piedraPerfeccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piel de bisonte.
        /// </summary>
        internal static string pielbisonte {
            get {
                return ResourceManager.GetString("pielbisonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pino.
        /// </summary>
        internal static string pino {
            get {
                return ResourceManager.GetString("pino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roble.
        /// </summary>
        internal static string roble {
            get {
                return ResourceManager.GetString("roble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roca caliza.
        /// </summary>
        internal static string rocaCaliza {
            get {
                return ResourceManager.GetString("rocaCaliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seda.
        /// </summary>
        internal static string seda {
            get {
                return ResourceManager.GetString("seda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siderita.
        /// </summary>
        internal static string siderita {
            get {
                return ResourceManager.GetString("siderita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tejo.
        /// </summary>
        internal static string tejo {
            get {
                return ResourceManager.GetString("tejo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tela áspera.
        /// </summary>
        internal static string telaAspera {
            get {
                return ResourceManager.GetString("telaAspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tela barata.
        /// </summary>
        internal static string telaBarata {
            get {
                return ResourceManager.GetString("telaBarata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tela Excelente.
        /// </summary>
        internal static string telaExceletne {
            get {
                return ResourceManager.GetString("telaExceletne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tendones.
        /// </summary>
        internal static string tendones {
            get {
                return ResourceManager.GetString("tendones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tungsteno.
        /// </summary>
        internal static string tungsteno {
            get {
                return ResourceManager.GetString("tungsteno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turquesa.
        /// </summary>
        internal static string turquesa {
            get {
                return ResourceManager.GetString("turquesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piel de vaca.
        /// </summary>
        internal static string vaca {
            get {
                return ResourceManager.GetString("vaca", resourceCulture);
            }
        }
    }
}
