//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conqueros_Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conqueros_Calculator.Properties.idioma", typeof(idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aceitelinaza.
        /// </summary>
        internal static string aceitelinaza {
            get {
                return ResourceManager.GetString("aceitelinaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alerce.
        /// </summary>
        internal static string alerce {
            get {
                return ResourceManager.GetString("alerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algodonAltaCalidad.
        /// </summary>
        internal static string algodonAltaCalidad {
            get {
                return ResourceManager.GetString("algodonAltaCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algodonMediaCalidad.
        /// </summary>
        internal static string algodonMediaCalidad {
            get {
                return ResourceManager.GetString("algodonMediaCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algodonMejorCalidad.
        /// </summary>
        internal static string algodonMejorCalidad {
            get {
                return ResourceManager.GetString("algodonMejorCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algodonMontaña.
        /// </summary>
        internal static string algodonMontaña {
            get {
                return ResourceManager.GetString("algodonMontaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algodonNube.
        /// </summary>
        internal static string algodonNube {
            get {
                return ResourceManager.GetString("algodonNube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a algodonPocaCalidad.
        /// </summary>
        internal static string algodonPocaCalidad {
            get {
                return ResourceManager.GetString("algodonPocaCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a almizcle.
        /// </summary>
        internal static string almizcle {
            get {
                return ResourceManager.GetString("almizcle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alumbre.
        /// </summary>
        internal static string alumbre {
            get {
                return ResourceManager.GetString("alumbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ambar.
        /// </summary>
        internal static string ambar {
            get {
                return ResourceManager.GetString("ambar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a arenisca.
        /// </summary>
        internal static string arenisca {
            get {
                return ResourceManager.GetString("arenisca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bauxitamontaña.
        /// </summary>
        internal static string bauxitamontaña {
            get {
                return ResourceManager.GetString("bauxitamontaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cabra.
        /// </summary>
        internal static string cabra {
            get {
                return ResourceManager.GetString("cabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a calamina.
        /// </summary>
        internal static string calamina {
            get {
                return ResourceManager.GetString("calamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a calcopirita.
        /// </summary>
        internal static string calcopirita {
            get {
                return ResourceManager.GetString("calcopirita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a calcosina.
        /// </summary>
        internal static string calcosina {
            get {
                return ResourceManager.GetString("calcosina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cañamo.
        /// </summary>
        internal static string cañamo {
            get {
                return ResourceManager.GetString("cañamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a carbon.
        /// </summary>
        internal static string carbon {
            get {
                return ResourceManager.GetString("carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cedro.
        /// </summary>
        internal static string cedro {
            get {
                return ResourceManager.GetString("cedro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cerdo.
        /// </summary>
        internal static string cerdo {
            get {
                return ResourceManager.GetString("cerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobreBruto.
        /// </summary>
        internal static string cobreBruto {
            get {
                return ResourceManager.GetString("cobreBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobreMejorado.
        /// </summary>
        internal static string cobreMejorado {
            get {
                return ResourceManager.GetString("cobreMejorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobrePuro.
        /// </summary>
        internal static string cobrePuro {
            get {
                return ResourceManager.GetString("cobrePuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobreRefinado.
        /// </summary>
        internal static string cobreRefinado {
            get {
                return ResourceManager.GetString("cobreRefinado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroCurtido.
        /// </summary>
        internal static string cueroCurtido {
            get {
                return ResourceManager.GetString("cueroCurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroHervido.
        /// </summary>
        internal static string cueroHervido {
            get {
                return ResourceManager.GetString("cueroHervido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroPerfeccionado.
        /// </summary>
        internal static string cueroPerfeccionado {
            get {
                return ResourceManager.GetString("cueroPerfeccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cueroTratado.
        /// </summary>
        internal static string cueroTratado {
            get {
                return ResourceManager.GetString("cueroTratado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuprita.
        /// </summary>
        internal static string cuprita {
            get {
                return ResourceManager.GetString("cuprita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a digenita.
        /// </summary>
        internal static string digenita {
            get {
                return ResourceManager.GetString("digenita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estaño.
        /// </summary>
        internal static string estaño {
            get {
                return ResourceManager.GetString("estaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fosforo.
        /// </summary>
        internal static string fosforo {
            get {
                return ResourceManager.GetString("fosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fresno.
        /// </summary>
        internal static string fresno {
            get {
                return ResourceManager.GetString("fresno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gomalaca.
        /// </summary>
        internal static string gomalaca {
            get {
                return ResourceManager.GetString("gomalaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a granate.
        /// </summary>
        internal static string granate {
            get {
                return ResourceManager.GetString("granate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a granito.
        /// </summary>
        internal static string granito {
            get {
                return ResourceManager.GetString("granito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hematita.
        /// </summary>
        internal static string hematita {
            get {
                return ResourceManager.GetString("hematita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hierroBruto.
        /// </summary>
        internal static string hierroBruto {
            get {
                return ResourceManager.GetString("hierroBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hierroForjado.
        /// </summary>
        internal static string hierroForjado {
            get {
                return ResourceManager.GetString("hierroForjado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hierroFundido.
        /// </summary>
        internal static string hierroFundido {
            get {
                return ResourceManager.GetString("hierroFundido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hierroPuro.
        /// </summary>
        internal static string hierroPuro {
            get {
                return ResourceManager.GetString("hierroPuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a limonita.
        /// </summary>
        internal static string limonita {
            get {
                return ResourceManager.GetString("limonita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lino.
        /// </summary>
        internal static string lino {
            get {
                return ResourceManager.GetString("lino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maderaAlisada.
        /// </summary>
        internal static string maderaAlisada {
            get {
                return ResourceManager.GetString("maderaAlisada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maderaCompuesta.
        /// </summary>
        internal static string maderaCompuesta {
            get {
                return ResourceManager.GetString("maderaCompuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maderaSeca.
        /// </summary>
        internal static string maderaSeca {
            get {
                return ResourceManager.GetString("maderaSeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a magnetita.
        /// </summary>
        internal static string magnetita {
            get {
                return ResourceManager.GetString("magnetita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a manganesoNegro.
        /// </summary>
        internal static string manganesoNegro {
            get {
                return ResourceManager.GetString("manganesoNegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a marmol.
        /// </summary>
        internal static string marmol {
            get {
                return ResourceManager.GetString("marmol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minio.
        /// </summary>
        internal static string minio {
            get {
                return ResourceManager.GetString("minio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nitratopotasio.
        /// </summary>
        internal static string nitratopotasio {
            get {
                return ResourceManager.GetString("nitratopotasio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oveja.
        /// </summary>
        internal static string oveja {
            get {
                return ResourceManager.GetString("oveja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pelajelobomontaña.
        /// </summary>
        internal static string pelajelobomontaña {
            get {
                return ResourceManager.GetString("pelajelobomontaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pelajes.
        /// </summary>
        internal static string pelajes {
            get {
                return ResourceManager.GetString("pelajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piedraBruto.
        /// </summary>
        internal static string piedraBruto {
            get {
                return ResourceManager.GetString("piedraBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piedraCortada.
        /// </summary>
        internal static string piedraCortada {
            get {
                return ResourceManager.GetString("piedraCortada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piedraDetallada.
        /// </summary>
        internal static string piedraDetallada {
            get {
                return ResourceManager.GetString("piedraDetallada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piedralunar.
        /// </summary>
        internal static string piedralunar {
            get {
                return ResourceManager.GetString("piedralunar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piedraPerfeccionada.
        /// </summary>
        internal static string piedraPerfeccionada {
            get {
                return ResourceManager.GetString("piedraPerfeccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pielbisonte.
        /// </summary>
        internal static string pielbisonte {
            get {
                return ResourceManager.GetString("pielbisonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pino.
        /// </summary>
        internal static string pino {
            get {
                return ResourceManager.GetString("pino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a roble.
        /// </summary>
        internal static string roble {
            get {
                return ResourceManager.GetString("roble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rocaCaliza.
        /// </summary>
        internal static string rocaCaliza {
            get {
                return ResourceManager.GetString("rocaCaliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seda.
        /// </summary>
        internal static string seda {
            get {
                return ResourceManager.GetString("seda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a siderita.
        /// </summary>
        internal static string siderita {
            get {
                return ResourceManager.GetString("siderita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tejo.
        /// </summary>
        internal static string tejo {
            get {
                return ResourceManager.GetString("tejo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a telaAspera.
        /// </summary>
        internal static string telaAspera {
            get {
                return ResourceManager.GetString("telaAspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a telaBarata.
        /// </summary>
        internal static string telaBarata {
            get {
                return ResourceManager.GetString("telaBarata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a telaExceletne.
        /// </summary>
        internal static string telaExceletne {
            get {
                return ResourceManager.GetString("telaExceletne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tendones.
        /// </summary>
        internal static string tendones {
            get {
                return ResourceManager.GetString("tendones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tungsteno.
        /// </summary>
        internal static string tungsteno {
            get {
                return ResourceManager.GetString("tungsteno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a turquesa.
        /// </summary>
        internal static string turquesa {
            get {
                return ResourceManager.GetString("turquesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vaca.
        /// </summary>
        internal static string vaca {
            get {
                return ResourceManager.GetString("vaca", resourceCulture);
            }
        }
    }
}
